target-version = "py312"
exclude = [".git", ".venv", ".vscode"]

[lint]
select = [
    "E",       # pycodestyle errors
    "W",       # pycodestyle warnings
    "F",       # pyflakes
    "I",       # isort
    "B",       # flake8-bugbear
    "C4",      # flake8-comprehensions
    "UP",      # pyupgrade
    "ARG001",  # unused arguments in functions
    "FAST001", # FastAPI route with redundant response_model argument
    "FAST002", # FastAPI dependency without Annotated
]

fixable = ["ALL"]

[lint.per-file-ignores]
"__init__.py" = ["E402"]
